import type { Lead, Message, Service, Promotion, Payment, InternalNote } from '@/types'

export const MOCK_SERVICES: Service[] = [
  {
    id: 'srv-1',
    name: 'Carnet B — Pack 90 €',
    category: 'coche',
    price: 90,
    short_description: 'Pack básico carnet de coche',
    includes: ['Matrícula', 'Curso teórico completo', 'Libro oficial', 'Test en aula ilimitados', 'Test online durante 1 mes', 'Placa L'],
    extras: [],
    payment_link: 'https://buy.stripe.com/fZueVcaDf80vb7DeL83Je08',
    active: true,
    sort_order: 1,
    internal_notes: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'srv-2',
    name: 'Carnet B — Pack 295 €',
    category: 'coche',
    price: 295,
    short_description: 'Pack completo con prácticas y tasas incluidas',
    includes: ['Matrícula', 'Curso teórico completo', 'Libro oficial', 'Test en aula ilimitados', 'Test online durante 3 meses', 'Placa L', 'Tasas de Tráfico incluidas', '4 clases prácticas de 40 min'],
    extras: [],
    payment_link: 'https://buy.stripe.com/dRm00idPr1C7fnT9qO3Je07',
    active: true,
    sort_order: 2,
    internal_notes: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'srv-3',
    name: 'Moto A1/A2 — 220 €',
    category: 'moto',
    price: 220,
    short_description: 'Pack moto A1/A2 con prácticas en pista',
    includes: ['Tasas de tráfico', 'Matrícula', 'Libro y test en aula', '3 clases prácticas en pista de 30 min', 'Test online durante 1 mes'],
    extras: [{ name: 'Clase pista 30 min', price: 20 }, { name: 'Clase circulación 60 min', price: 60 }],
    payment_link: 'https://buy.stripe.com/5kQ7sKcLncgLa3z7iG3Je04',
    active: true,
    sort_order: 3,
    internal_notes: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'srv-4',
    name: 'Moto A — 350 €',
    category: 'moto',
    price: 350,
    short_description: 'Pack moto A con intensivo teórico y prácticas completas',
    includes: ['Matrícula / alta en la autoescuela', 'Gestión inicial del expediente', 'Curso teórico intensivo de 3 horas', '2 horas de clases de pista', '4 horas de clases de circulación'],
    extras: [],
    payment_link: 'https://buy.stripe.com/8x2dR85iV4OjejP6eC3Je05',
    active: true,
    sort_order: 4,
    internal_notes: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const MOCK_LEADS: Lead[] = [
  {
    id: 'lead-1',
    name: 'Carlos Martínez',
    phone: '654321987',
    email: 'carlos@example.com',
    interest: 'Carnet B',
    selected_service_id: 'srv-2',
    selected_pack: 'Pack 295 €',
    status: 'payment_link_sent',
    payment_status: 'unpaid',
    stripe_customer_id: null,
    last_message: '¿El pack de 295€ incluye las tasas de Tráfico?',
    summary: 'Interesado en Carnet B Pack 295€. Se le envió link de pago. Pendiente de confirmar.',
    source: 'whatsapp',
    requires_human: false,
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead-2',
    name: 'María González',
    phone: '612345678',
    email: null,
    interest: 'Moto A1/A2',
    selected_service_id: 'srv-3',
    selected_pack: null,
    status: 'paid',
    payment_status: 'paid',
    stripe_customer_id: null,
    last_message: '¡Perfecto, acabo de pagar!',
    summary: 'Pagó el pack de Moto A1/A2. Alumna nueva confirmada.',
    source: 'whatsapp',
    requires_human: false,
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead-3',
    name: null,
    phone: '699887766',
    email: null,
    interest: null,
    selected_service_id: null,
    selected_pack: null,
    status: 'pending_human',
    payment_status: 'unpaid',
    stripe_customer_id: null,
    last_message: 'Dice que pagó hace 3 días pero no le han contactado',
    summary: 'Cliente con problema de pago. Requiere atención humana urgente.',
    source: 'whatsapp',
    requires_human: true,
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead-4',
    name: 'Alejandro Ruiz',
    phone: '678901234',
    email: 'alex.ruiz@gmail.com',
    interest: 'Carnet B',
    selected_service_id: 'srv-1',
    selected_pack: 'Pack 90 €',
    status: 'interested',
    payment_status: 'unpaid',
    stripe_customer_id: null,
    last_message: '¿Cuánto tiempo tarda en sacar el carnet?',
    summary: 'Interesado en Pack 90€. Preguntó por plazos orientativos.',
    source: 'whatsapp',
    requires_human: false,
    created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead-5',
    name: 'Lucía Fernández',
    phone: '655443322',
    email: null,
    interest: 'Moto A',
    selected_service_id: 'srv-4',
    selected_pack: null,
    status: 'new',
    payment_status: 'unpaid',
    stripe_customer_id: null,
    last_message: 'Hola, quiero información sobre el carnet de moto',
    summary: 'Lead nuevo. Preguntó por información sobre moto A.',
    source: 'whatsapp',
    requires_human: false,
    created_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
]

export const MOCK_MESSAGES: Record<string, Message[]> = {
  'lead-1': [
    { id: 'm1', lead_id: 'lead-1', direction: 'inbound', sender_type: 'user', content: 'Hola, quiero información sobre el carnet de coche', whatsapp_message_id: null, created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString() },
    { id: 'm2', lead_id: 'lead-1', direction: 'outbound', sender_type: 'bot', content: '¡Hola! Soy el asistente de Autoescuela Airbag 🚗\n\nTenemos dos opciones para el Carnet B:\n\n• Pack 90 € — Incluye teoría, libro y test online 1 mes\n• Pack 295 € — Todo lo anterior + tasas de Tráfico + 4 clases prácticas\n\n¿Cuál te interesa más?', whatsapp_message_id: null, created_at: new Date(Date.now() - 4.5 * 60 * 60 * 1000).toISOString() },
    { id: 'm3', lead_id: 'lead-1', direction: 'inbound', sender_type: 'user', content: '¿El pack de 295€ incluye las tasas de Tráfico?', whatsapp_message_id: null, created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString() },
    { id: 'm4', lead_id: 'lead-1', direction: 'outbound', sender_type: 'bot', content: '¡Sí! El Pack 295 € incluye todo:\n\n✅ Matrícula\n✅ Curso teórico completo\n✅ Libro oficial\n✅ Test en aula ilimitados\n✅ Test online 3 meses\n✅ Placa L\n✅ Tasas de Tráfico\n✅ 4 clases prácticas de 40 min\n\nPuedes reservar tu plaza aquí: https://buy.stripe.com/dRm00idPr1C7fnT9qO3Je07', whatsapp_message_id: null, created_at: new Date(Date.now() - 55 * 60 * 1000).toISOString() },
  ],
  'lead-2': [
    { id: 'm5', lead_id: 'lead-2', direction: 'inbound', sender_type: 'user', content: 'Buenas, quiero el carnet de moto A1', whatsapp_message_id: null, created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString() },
    { id: 'm6', lead_id: 'lead-2', direction: 'outbound', sender_type: 'bot', content: '¡Hola! Para la Moto A1/A2 tenemos un pack a 220 €\n\nIncluye:\n✅ Tasas de tráfico\n✅ Matrícula\n✅ Libro y test en aula\n✅ 3 clases prácticas en pista de 30 min\n✅ Test online 1 mes\n\nReserva aquí: https://buy.stripe.com/5kQ7sKcLncgLa3z7iG3Je04', whatsapp_message_id: null, created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000 + 5 * 60 * 1000).toISOString() },
    { id: 'm7', lead_id: 'lead-2', direction: 'inbound', sender_type: 'user', content: '¡Perfecto, acabo de pagar!', whatsapp_message_id: null, created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString() },
    { id: 'm8', lead_id: 'lead-2', direction: 'outbound', sender_type: 'bot', content: '¡Genial, María! 🎉 Hemos recibido tu pago. El equipo de Autoescuela Airbag se pondrá en contacto contigo para confirmar los próximos pasos.\n\nCualquier duda, llámanos al 955 542 232', whatsapp_message_id: null, created_at: new Date(Date.now() - 2.9 * 60 * 60 * 1000).toISOString() },
  ],
}

export const MOCK_PROMOTIONS: Promotion[] = []

export const MOCK_PAYMENTS: Payment[] = [
  {
    id: 'pay-1',
    lead_id: 'lead-2',
    stripe_payment_id: 'pi_3QxKlMExample001',
    stripe_checkout_session_id: 'cs_test_example001',
    stripe_customer_id: null,
    customer_name: 'María González',
    customer_email: null,
    customer_phone: '612345678',
    product_name: 'Moto A1/A2 — 220 €',
    service_id: 'srv-3',
    amount: 22000,
    currency: 'eur',
    status: 'succeeded',
    paid_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    raw_payload: null,
    created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
]

export const MOCK_NOTES: Record<string, InternalNote[]> = {
  'lead-3': [
    {
      id: 'note-1',
      lead_id: 'lead-3',
      note: 'Llamar urgente. Dice que tiene justificante de pago pero no aparece en Stripe.',
      created_at: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    },
  ],
}

export const MOCK_SETTINGS: Record<string, string> = {
  school_name: 'Autoescuela Airbag',
  school_phone: '955 542 232',
  school_email: 'info@aeairbag.com',
  school_address: 'C. Navarro Caro, Tomares, Sevilla',
  school_hours: '10:00 a 13:00 y 17:00 a 20:00',
  school_web: 'https://aeairbag.com',
  chatbot_active: 'true',
  welcome_message: '¡Hola! Soy el asistente de Autoescuela Airbag 🚗🏍️\n\nTe ayudo a consultar precios, elegir carnet, resolver dudas y reservar tu plaza.\n\n¿Qué necesitas?\n\n1. Carnet de coche B\n2. Carnet moto A1/A2\n3. Carnet moto A\n4. Test online\n5. Plazos y documentación\n6. Hablar con la autoescuela',
  handoff_message: 'Para esto es mejor que te atienda directamente el equipo de Autoescuela Airbag, así te dan una respuesta exacta.\n\n📞 Teléfono: 955 542 232\n✉️ Email: info@aeairbag.com\n📍 Dirección: C. Navarro Caro, Tomares, Sevilla\n🕒 Horario: 10:00 a 13:00 y 17:00 a 20:00',
}
